### ISSUE TITLE
how to find the Tumor of the swapped samples

### ISSUE THREAD

**Issue by tangwei1129** [nygenome/Conpair#2]
I have used the Conpair to find the swapped samples successfully, but I came with new issue is how can I be sure that which sample is the Tumor samples? Thank you

**Comment by ewabergmann** [comment]
Conpair shows concordance between two samples based on the set of germline markers. Based on this value you cannot tell which sample is tumor and which is normal. 

There are 2 things you could potentially do, both are based on the assumption that the tumor sample would contain multiple LOH events (which won't be true for quiet tumors with few CNVs):
1) based on the pileup files calculate genotypes ("0/0", "0/1", "1/1") for both concordant samples and check if one of the samples contains stretches of "0/0" and "1/1" while the other doesn't - this should be your tumor sample.
2) using Conpair estimate contamination for both combinations (1) sample A as tumor and sample B as normal 2) sample A as normal and sample B as tumor) and check if one of the combinations gives you a low contamination value - this should be the correct combination.

Hope this helps!
