### ISSUE TITLE
Whethter Conpair  is suitable for target panel sequencing for human ?

### ISSUE THREAD

**Issue by zeronot** [nygenome/Conpair#5]
HI,
     I wanna use Conpair to evaluate tumor-normal samples from  many genes  panel sequencing,however,
I am not sure if it's ok   ？
    genes panels have fewer the number of  sites and region length than WGS or WXS .

thank you!

**Comment by bec-p** [comment]
Hi, I am also interested in the answer to this question. My target-sequenced region is approximately the same size as WXS, but my sequenced regions only overlap ~10% of the GRCh37 markers in the CONPAIR/data/markers folder. Will Conpair be suitable for use in this dataset?

**Comment by ewabergmann** [comment]
Hi,
Unfortunately, Conpair has never been tested on targeted gene panel data. I would assume the higher overlap between the sequenced regions and the marker list, the more accurate the results are going to be. The accuracy would also gently depend on a specific panel, as different markers have slightly different allelic frequencies in the population.

The 10% overlap (~750 covered markers) sounds pretty good to me and I would expect the results would be pretty accurate. As I said, however, we have never tested Conpair specifically on the panel data.

Hope this helps,
Ewa

**Comment by WinterLi1993** [comment]
@ewabergmann  what's the difference between GATK-contEst and Conpair ??

**Comment by WinterLi1993** [comment]
@bec-p  what's  the GRCh37 markers ? what do you mean ?

**Comment by bec-p** [comment]
@ewabergmann Thanks for your help. I have run Conpair on our targeted sequencing data and the results suggest that the tool works fine for this data type. Thanks for the helpful program!

@WinterLi1993 In the CONPAIR folder, under data/markers/ is a file called  "GRCh37.autosomes.phase3_shapeit2_mvncall_integrated.20130502.SNV.genotype.sselect_v4_MAF_0.4_LD_0.8.bed". These are the markers that I am referring to.

**Comment by ewabergmann** [comment]
@bec-p: 👍 great, thanks for the info!

@WinterLi1993: Conpair is often more accurate on whole-genome and whole-exome than ContEst and does not require >50x coverage in both the tumor and the normal sample (or a genotyping array).

For more information please see the Supplementary Data: https://academic.oup.com/bioinformatics/article/32/20/3196/2196627/Conpair-concordance-and-contamination-estimator

**Comment by asmlgkj** [comment]
@rcpoulos thanks a lot. hi, what is the average depth of your panel,  I met error like 

WARNING: There are no shared markers between the tumor and the normal samples that meet the specified coverage requirements (10)
Is the coverage of your samples high enough?
Exiting...
